name: dash_app
channels:
    - conda-forge
dependencies:
    - python>=3.9.7
    - numpy
    - scipy
    - matplotlib
    - dash>=2.5.1
    - dash-bootstrap-components>=1.2.0
    - plotly
    - glom
    - diskcache
    - celery
    - redis
    - pip
    - pip:
        - gunicorn
        - dash-extensions>=0.1.1
        - flask-caching>=1.10.1
        - git+https://github.com/ZBT-Tools/pemfc-core.git@master#egg=pemfc
        - git+https://github.com/ZBT-Tools/pemfc-tkinter-app.git@master#egg=pemfc_gui


